version: '3.8'

networks:
  corp:
    driver: bridge

services:
  homepage-api:
    container_name: homepage-api
    build:
      context: ./
      cache_from:
        - base-image:nx-base
      dockerfile: ./apps/homepage-api/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: homepage-api:nx-dev
    ports:
      - 4939:4939
    environment:
      NODE_ENV: 'development'
      PORT: 4939
      NX_HOMEPAGE_APP_URL: http://localhost:4200
      NX_HOMEPAGE_API_URL: http://localhost:4939
      NX_AZURE_KV_NAME: kv-sandbox-vnext-dt-wus
      WB_API_URL: url
      NX_MANAGED_IDENTITY_CLIENT_ID: '58b8ed09-7042-46e2-b783-75c9babfc5f1'
    networks:
      - corp
    restart: on-failure

  homepage-app:
    container_name: homepage-app
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/homepage-app/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: homepage-app:nx-dev
    ports:
      - 4200:80
    environment:
      NODE_ENV: 'development'
      PORT: 4200
      NX_HOMEPAGE_APP_URL: http://localhost:4200
      NX_HOMEPAGE_API_URL: http://localhost:4939
      NX_AZURE_KV_NAME: kv-sandbox-vnext-dt-wus
      WB_API_URL: url
      NX_MANAGED_IDENTITY_CLIENT_ID: '58b8ed09-7042-46e2-b783-75c9babfc5f1'
    networks:
      - corp
    restart: on-failure
