version: '3.8'

networks:
  corp:
    driver: bridge

services:
  homepage-api:
    container_name: homepage-api
    build:
      context: ./
      cache_from:
        - base-image:nx-base
      dockerfile: ./apps/homepage-api/Dockerfile.dev
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: homepage-api:nx-dev
    ports:
      - 4940:4940
    environment:
      NODE_ENV: 'development'
      PORT: 4940
    networks:
      - corp
    restart: always
    volumes:
      - ./:/app

  homepage-app:
    container_name: homepage-app
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/homepage-app/Dockerfile.dev
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: homepage-app:nx-dev
    ports:
      - 3005:80
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      NODE_ENV: 'development'
      PORT: 3005
    networks:
      - corp
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
