export const config = {
  HOMEPAGE_APP_URL: process.env.NX_HOMEPAGE_APP_URL,
  HOMEPAGE_API_URL: process.env.NX_HOMEPAGE_API_URL,
  AZURE_KV_NAME: process.env.NX_AZURE_KV_NAME,
  MANAGED_IDENTITY_CLIENT_ID: process.env.NX_MANAGED_IDENTITY_CLIENT_ID,
  VNEXT_SANDBOX_SECRET: process.env.VNEXT_SANDBOX_SECRET,
};
