export const config = {
  HOMEPAGE_APP_URL: process.env.NX_HOMEPAGE_APP_URL,
  HOMEPAGE_APP_CLIENT_ID: process.env.NX_HOMEPAGE_APP_CLIENT_ID,
  HOMEPAGE_API_URL: process.env.NX_HOMEPAGE_API_URL,
  AZURE_KV_NAME: process.env.NX_AZURE_KV_NAME,
  MANAGED_IDENTITY_CLIENT_ID: process.env.NX_MANAGED_IDENTITY_CLIENT_ID,
  VNEXT_SANDBOX_SECRET: process.env.VNEXT_SANDBOX_SECRET,
  NODEJS_CREDENTIAL_WB_INTERNAL_TOKEN: process.env.NX_NODEJS_CREDENTIAL_WB_INTERNAL_TOKEN,
  SHARED_SECRET: process.env.NX_PROXY_SHARED_SECRET,
  WB_BASE_URL : process.env.NX_WB_BASE_URL,
  AUTH_PROXY_URI : process.env.NX_AUTH_PROXY_URI,
  AUTH_ENCRYPTION_SECRET: process.env.NX_ENCRYPTION_SECRET
};
