FROM base-image:nx-base AS builder

ARG NODE_ENV
ARG BUILD_FLAG
WORKDIR /app/builder
COPY . .
RUN npx nx build homepage-bff ${BUILD_FLAG}

FROM base-image:nx-base

WORKDIR /app
COPY --from=builder /app/builder ./
ENV NODE_ENV=$NODE_ENV


CMD ["npx", "nx", "serve", "homepage-bff"]
